spring.application.name=EduTrack
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/student_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

# Execute schema.sql on startup
spring.sql.init.mode=always
spring.sql.init.platform=postgres

# Logging
logging.level.root=INFO
logging.level.com.example.student=DEBUG

